name: Tox

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  tox:
    strategy:
      matrix:
        package: [by_literal, by_getattr, by_property]

        os:
        - ubuntu-22.04  # For Python 3.7 only (unavailable on >= 24.04).
        - ubuntu-latest
        - macos-13  # These images are x86-64 (amd64).
        - macos-15  # These images are Apple Silicon (aarch64, amd64).
        - windows-latest

        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']

        exclude:
        # Use Ubuntu 22.04 only to test Python 3.7, and no other Pythons.
        - os: ubuntu-22.04
          python-version: '3.8'
        - os: ubuntu-22.04
          python-version: '3.9'
        - os: ubuntu-22.04
          python-version: '3.10'
        - os: ubuntu-22.04
          python-version: '3.11'
        - os: ubuntu-22.04
          python-version: '3.12'
        - os: ubuntu-22.04
          python-version: '3.13'
        - os: ubuntu-22.04
          python-version: '3.14'

        # Python 3.7 is not available on some newer systems.
        - os: ubuntu-latest
          python-version: '3.7'
        - os: macos-15
          python-version: '3.7'

        include:
        - experimental: false

        - python-version: '3.14'
          experimental: true

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash --noprofile --norc -exo pipefail {0}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: ${{ matrix.experimental }}

    - name: Upgrade PyPA packages
      run: python -m pip install -U pip 'setuptools; python_version<"3.12"' wheel

    - name: Install tox and plugins
      run: pip install -U 'tox==4.*' 'tox-gh-actions==3.*'

    - name: Check with tox
      run: tox --root ${{ matrix.package }}

  all-pass:
    name: All tox checks pass

    needs: [tox]

    runs-on: ubuntu-latest

    steps:
    - name: Some failed
      if: contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')
      run: false

    - name: All passed
      run: true
